# coding: utf-8

"""
    Strava API v3

    The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import strava_python
from strava_python.models.activity_type import ActivityType  # noqa: E501
from strava_python.rest import ApiException

class TestActivityType(unittest.TestCase):
    """ActivityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivityType(self):
        """Test ActivityType"""
        # inst = ActivityType()

if __name__ == '__main__':
    unittest.main()
