# coding: utf-8

"""
    Strava API v3

    The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt

class ActivityTotal(BaseModel):
    """
    A roll-up of metrics pertaining to a set of activities. Values are in seconds and meters.
    """
    count: Optional[StrictInt] = Field(None, description="The number of activities considered in this total.")
    distance: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The total distance covered by the considered activities.")
    moving_time: Optional[StrictInt] = Field(None, description="The total moving time of the considered activities.")
    elapsed_time: Optional[StrictInt] = Field(None, description="The total elapsed time of the considered activities.")
    elevation_gain: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The total elevation gain of the considered activities.")
    achievement_count: Optional[StrictInt] = Field(None, description="The total number of achievements of the considered activities.")
    __properties = ["count", "distance", "moving_time", "elapsed_time", "elevation_gain", "achievement_count"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ActivityTotal:
        """Create an instance of ActivityTotal from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ActivityTotal:
        """Create an instance of ActivityTotal from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ActivityTotal.parse_obj(obj)

        _obj = ActivityTotal.parse_obj({
            "count": obj.get("count"),
            "distance": obj.get("distance"),
            "moving_time": obj.get("moving_time"),
            "elapsed_time": obj.get("elapsed_time"),
            "elevation_gain": obj.get("elevation_gain"),
            "achievement_count": obj.get("achievement_count")
        })
        return _obj


