# coding: utf-8

"""
    Strava API v3

    The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ActivityType(str, Enum):
    """
    An enumeration of the types an activity may have. Note that this enumeration does not include new sport types (e.g. MountainBikeRide, EMountainBikeRide), activities with these sport types will have the corresponding activity type (e.g. Ride for MountainBikeRide, EBikeRide for EMountainBikeRide)
    """

    """
    allowed enum values
    """
    ALPINESKI = 'AlpineSki'
    BACKCOUNTRYSKI = 'BackcountrySki'
    CANOEING = 'Canoeing'
    CROSSFIT = 'Crossfit'
    EBIKERIDE = 'EBikeRide'
    ELLIPTICAL = 'Elliptical'
    GOLF = 'Golf'
    HANDCYCLE = 'Handcycle'
    HIKE = 'Hike'
    ICESKATE = 'IceSkate'
    INLINESKATE = 'InlineSkate'
    KAYAKING = 'Kayaking'
    KITESURF = 'Kitesurf'
    NORDICSKI = 'NordicSki'
    RIDE = 'Ride'
    ROCKCLIMBING = 'RockClimbing'
    ROLLERSKI = 'RollerSki'
    ROWING = 'Rowing'
    RUN = 'Run'
    SAIL = 'Sail'
    SKATEBOARD = 'Skateboard'
    SNOWBOARD = 'Snowboard'
    SNOWSHOE = 'Snowshoe'
    SOCCER = 'Soccer'
    STAIRSTEPPER = 'StairStepper'
    STANDUPPADDLING = 'StandUpPaddling'
    SURFING = 'Surfing'
    SWIM = 'Swim'
    VELOMOBILE = 'Velomobile'
    VIRTUALRIDE = 'VirtualRide'
    VIRTUALRUN = 'VirtualRun'
    WALK = 'Walk'
    WEIGHTTRAINING = 'WeightTraining'
    WHEELCHAIR = 'Wheelchair'
    WINDSURF = 'Windsurf'
    WORKOUT = 'Workout'
    YOGA = 'Yoga'

    @classmethod
    def from_json(cls, json_str: str) -> ActivityType:
        """Create an instance of ActivityType from a JSON string"""
        return ActivityType(json.loads(json_str))


