# coding: utf-8

"""
    Strava API v3

    The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from strava_python.models.summary_athlete import SummaryAthlete

class Comment(BaseModel):
    """
    Comment
    """
    id: Optional[StrictInt] = Field(None, description="The unique identifier of this comment")
    activity_id: Optional[StrictInt] = Field(None, description="The identifier of the activity this comment is related to")
    text: Optional[StrictStr] = Field(None, description="The content of the comment")
    athlete: Optional[SummaryAthlete] = None
    created_at: Optional[datetime] = Field(None, description="The time at which this comment was created.")
    __properties = ["id", "activity_id", "text", "athlete", "created_at"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Comment:
        """Create an instance of Comment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of athlete
        if self.athlete:
            _dict['athlete'] = self.athlete.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Comment:
        """Create an instance of Comment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Comment.parse_obj(obj)

        _obj = Comment.parse_obj({
            "id": obj.get("id"),
            "activity_id": obj.get("activity_id"),
            "text": obj.get("text"),
            "athlete": SummaryAthlete.from_dict(obj.get("athlete")) if obj.get("athlete") is not None else None,
            "created_at": obj.get("created_at")
        })
        return _obj


