# coding: utf-8

"""
    Strava API v3

    The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr, conint
from strava_python.models.meta_activity import MetaActivity
from strava_python.models.meta_athlete import MetaAthlete
from strava_python.models.summary_segment import SummarySegment

class DetailedSegmentEffort(BaseModel):
    """
    DetailedSegmentEffort
    """
    id: Optional[StrictInt] = Field(None, description="The unique identifier of this effort")
    activity_id: Optional[StrictInt] = Field(None, description="The unique identifier of the activity related to this effort")
    elapsed_time: Optional[StrictInt] = Field(None, description="The effort's elapsed time")
    start_date: Optional[datetime] = Field(None, description="The time at which the effort was started.")
    start_date_local: Optional[datetime] = Field(None, description="The time at which the effort was started in the local timezone.")
    distance: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The effort's distance in meters")
    is_kom: Optional[StrictBool] = Field(None, description="Whether this effort is the current best on the leaderboard")
    name: Optional[StrictStr] = Field(None, description="The name of the segment on which this effort was performed")
    activity: Optional[MetaActivity] = None
    athlete: Optional[MetaAthlete] = None
    moving_time: Optional[StrictInt] = Field(None, description="The effort's moving time")
    start_index: Optional[StrictInt] = Field(None, description="The start index of this effort in its activity's stream")
    end_index: Optional[StrictInt] = Field(None, description="The end index of this effort in its activity's stream")
    average_cadence: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The effort's average cadence")
    average_watts: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The average wattage of this effort")
    device_watts: Optional[StrictBool] = Field(None, description="For riding efforts, whether the wattage was reported by a dedicated recording device")
    average_heartrate: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The heart heart rate of the athlete during this effort")
    max_heartrate: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The maximum heart rate of the athlete during this effort")
    segment: Optional[SummarySegment] = None
    kom_rank: Optional[conint(strict=True, le=10, ge=1)] = Field(None, description="The rank of the effort on the global leaderboard if it belongs in the top 10 at the time of upload")
    pr_rank: Optional[conint(strict=True, le=3, ge=1)] = Field(None, description="The rank of the effort on the athlete's leaderboard if it belongs in the top 3 at the time of upload")
    hidden: Optional[StrictBool] = Field(None, description="Whether this effort should be hidden when viewed within an activity")
    __properties = ["id", "activity_id", "elapsed_time", "start_date", "start_date_local", "distance", "is_kom", "name", "activity", "athlete", "moving_time", "start_index", "end_index", "average_cadence", "average_watts", "device_watts", "average_heartrate", "max_heartrate", "segment", "kom_rank", "pr_rank", "hidden"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DetailedSegmentEffort:
        """Create an instance of DetailedSegmentEffort from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of activity
        if self.activity:
            _dict['activity'] = self.activity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of athlete
        if self.athlete:
            _dict['athlete'] = self.athlete.to_dict()
        # override the default output from pydantic by calling `to_dict()` of segment
        if self.segment:
            _dict['segment'] = self.segment.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DetailedSegmentEffort:
        """Create an instance of DetailedSegmentEffort from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DetailedSegmentEffort.parse_obj(obj)

        _obj = DetailedSegmentEffort.parse_obj({
            "id": obj.get("id"),
            "activity_id": obj.get("activity_id"),
            "elapsed_time": obj.get("elapsed_time"),
            "start_date": obj.get("start_date"),
            "start_date_local": obj.get("start_date_local"),
            "distance": obj.get("distance"),
            "is_kom": obj.get("is_kom"),
            "name": obj.get("name"),
            "activity": MetaActivity.from_dict(obj.get("activity")) if obj.get("activity") is not None else None,
            "athlete": MetaAthlete.from_dict(obj.get("athlete")) if obj.get("athlete") is not None else None,
            "moving_time": obj.get("moving_time"),
            "start_index": obj.get("start_index"),
            "end_index": obj.get("end_index"),
            "average_cadence": obj.get("average_cadence"),
            "average_watts": obj.get("average_watts"),
            "device_watts": obj.get("device_watts"),
            "average_heartrate": obj.get("average_heartrate"),
            "max_heartrate": obj.get("max_heartrate"),
            "segment": SummarySegment.from_dict(obj.get("segment")) if obj.get("segment") is not None else None,
            "kom_rank": obj.get("kom_rank"),
            "pr_rank": obj.get("pr_rank"),
            "hidden": obj.get("hidden")
        })
        return _obj


