# coding: utf-8

"""
    Strava API v3

    The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel
from strava_python.models.heart_rate_zone_ranges import HeartRateZoneRanges
from strava_python.models.power_zone_ranges import PowerZoneRanges

class Zones(BaseModel):
    """
    Zones
    """
    heart_rate: Optional[HeartRateZoneRanges] = None
    power: Optional[PowerZoneRanges] = None
    __properties = ["heart_rate", "power"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Zones:
        """Create an instance of Zones from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of heart_rate
        if self.heart_rate:
            _dict['heart_rate'] = self.heart_rate.to_dict()
        # override the default output from pydantic by calling `to_dict()` of power
        if self.power:
            _dict['power'] = self.power.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Zones:
        """Create an instance of Zones from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Zones.parse_obj(obj)

        _obj = Zones.parse_obj({
            "heart_rate": HeartRateZoneRanges.from_dict(obj.get("heart_rate")) if obj.get("heart_rate") is not None else None,
            "power": PowerZoneRanges.from_dict(obj.get("power")) if obj.get("power") is not None else None
        })
        return _obj


