# coding: utf-8

"""
    Strava API v3

    The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError
from typing_extensions import Annotated

from datetime import datetime

from pydantic import Field, StrictInt

from typing import List, Optional

from strava_python.models.detailed_segment_effort import DetailedSegmentEffort

from strava_python.api_client import ApiClient
from strava_python.api_response import ApiResponse
from strava_python.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class SegmentEffortsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def get_efforts_by_segment_id(self, segment_id : Annotated[StrictInt, Field(..., description="The identifier of the segment.")], start_date_local : Annotated[Optional[datetime], Field(description="ISO 8601 formatted date time.")] = None, end_date_local : Annotated[Optional[datetime], Field(description="ISO 8601 formatted date time.")] = None, per_page : Annotated[Optional[StrictInt], Field(description="Number of items per page. Defaults to 30.")] = None, **kwargs) -> List[DetailedSegmentEffort]:  # noqa: E501
        """List Segment Efforts  # noqa: E501

        Returns a set of the authenticated athlete's segment efforts for a given segment.  Requires subscription.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_efforts_by_segment_id(segment_id, start_date_local, end_date_local, per_page, async_req=True)
        >>> result = thread.get()

        :param segment_id: The identifier of the segment. (required)
        :type segment_id: int
        :param start_date_local: ISO 8601 formatted date time.
        :type start_date_local: datetime
        :param end_date_local: ISO 8601 formatted date time.
        :type end_date_local: datetime
        :param per_page: Number of items per page. Defaults to 30.
        :type per_page: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[DetailedSegmentEffort]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the get_efforts_by_segment_id_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        return self.get_efforts_by_segment_id_with_http_info(segment_id, start_date_local, end_date_local, per_page, **kwargs)  # noqa: E501

    @validate_arguments
    def get_efforts_by_segment_id_with_http_info(self, segment_id : Annotated[StrictInt, Field(..., description="The identifier of the segment.")], start_date_local : Annotated[Optional[datetime], Field(description="ISO 8601 formatted date time.")] = None, end_date_local : Annotated[Optional[datetime], Field(description="ISO 8601 formatted date time.")] = None, per_page : Annotated[Optional[StrictInt], Field(description="Number of items per page. Defaults to 30.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """List Segment Efforts  # noqa: E501

        Returns a set of the authenticated athlete's segment efforts for a given segment.  Requires subscription.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_efforts_by_segment_id_with_http_info(segment_id, start_date_local, end_date_local, per_page, async_req=True)
        >>> result = thread.get()

        :param segment_id: The identifier of the segment. (required)
        :type segment_id: int
        :param start_date_local: ISO 8601 formatted date time.
        :type start_date_local: datetime
        :param end_date_local: ISO 8601 formatted date time.
        :type end_date_local: datetime
        :param per_page: Number of items per page. Defaults to 30.
        :type per_page: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[DetailedSegmentEffort], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'segment_id',
            'start_date_local',
            'end_date_local',
            'per_page'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_efforts_by_segment_id" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('segment_id') is not None:  # noqa: E501
            _query_params.append(('segment_id', _params['segment_id']))

        if _params.get('start_date_local') is not None:  # noqa: E501
            if isinstance(_params['start_date_local'], datetime):
                _query_params.append(('start_date_local', _params['start_date_local'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('start_date_local', _params['start_date_local']))

        if _params.get('end_date_local') is not None:  # noqa: E501
            if isinstance(_params['end_date_local'], datetime):
                _query_params.append(('end_date_local', _params['end_date_local'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('end_date_local', _params['end_date_local']))

        if _params.get('per_page') is not None:  # noqa: E501
            _query_params.append(('per_page', _params['per_page']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['strava_oauth']  # noqa: E501

        _response_types_map = {
            '200': "List[DetailedSegmentEffort]",
        }

        return self.api_client.call_api(
            '/segment_efforts', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_segment_effort_by_id(self, id : Annotated[StrictInt, Field(..., description="The identifier of the segment effort.")], **kwargs) -> DetailedSegmentEffort:  # noqa: E501
        """Get Segment Effort  # noqa: E501

        Returns a segment effort from an activity that is owned by the authenticated athlete. Requires subscription.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_segment_effort_by_id(id, async_req=True)
        >>> result = thread.get()

        :param id: The identifier of the segment effort. (required)
        :type id: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: DetailedSegmentEffort
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the get_segment_effort_by_id_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        return self.get_segment_effort_by_id_with_http_info(id, **kwargs)  # noqa: E501

    @validate_arguments
    def get_segment_effort_by_id_with_http_info(self, id : Annotated[StrictInt, Field(..., description="The identifier of the segment effort.")], **kwargs) -> ApiResponse:  # noqa: E501
        """Get Segment Effort  # noqa: E501

        Returns a segment effort from an activity that is owned by the authenticated athlete. Requires subscription.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_segment_effort_by_id_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param id: The identifier of the segment effort. (required)
        :type id: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(DetailedSegmentEffort, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_segment_effort_by_id" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['id']:
            _path_params['id'] = _params['id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['strava_oauth']  # noqa: E501

        _response_types_map = {
            '200': "DetailedSegmentEffort",
        }

        return self.api_client.call_api(
            '/segment_efforts/{id}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
