# coding: utf-8

"""
    Strava API v3

    The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError
from typing_extensions import Annotated

from pydantic import Field, StrictBytes, StrictInt, StrictStr

from typing import Optional, Union

from strava_python.models.upload import Upload

from strava_python.api_client import ApiClient
from strava_python.api_response import ApiResponse
from strava_python.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class UploadsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def create_upload(self, file : Annotated[Optional[Union[StrictBytes, StrictStr]], Field(description="The uploaded file.")] = None, name : Annotated[Optional[StrictStr], Field(description="The desired name of the resulting activity.")] = None, description : Annotated[Optional[StrictStr], Field(description="The desired description of the resulting activity.")] = None, trainer : Annotated[Optional[StrictStr], Field(description="Whether the resulting activity should be marked as having been performed on a trainer.")] = None, commute : Annotated[Optional[StrictStr], Field(description="Whether the resulting activity should be tagged as a commute.")] = None, data_type : Annotated[Optional[StrictStr], Field(description="The format of the uploaded file.")] = None, external_id : Annotated[Optional[StrictStr], Field(description="The desired external identifier of the resulting activity.")] = None, **kwargs) -> Upload:  # noqa: E501
        """Upload Activity  # noqa: E501

        Uploads a new data file to create an activity from. Requires activity:write scope.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_upload(file, name, description, trainer, commute, data_type, external_id, async_req=True)
        >>> result = thread.get()

        :param file: The uploaded file.
        :type file: bytearray
        :param name: The desired name of the resulting activity.
        :type name: str
        :param description: The desired description of the resulting activity.
        :type description: str
        :param trainer: Whether the resulting activity should be marked as having been performed on a trainer.
        :type trainer: str
        :param commute: Whether the resulting activity should be tagged as a commute.
        :type commute: str
        :param data_type: The format of the uploaded file.
        :type data_type: str
        :param external_id: The desired external identifier of the resulting activity.
        :type external_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Upload
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the create_upload_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        return self.create_upload_with_http_info(file, name, description, trainer, commute, data_type, external_id, **kwargs)  # noqa: E501

    @validate_arguments
    def create_upload_with_http_info(self, file : Annotated[Optional[Union[StrictBytes, StrictStr]], Field(description="The uploaded file.")] = None, name : Annotated[Optional[StrictStr], Field(description="The desired name of the resulting activity.")] = None, description : Annotated[Optional[StrictStr], Field(description="The desired description of the resulting activity.")] = None, trainer : Annotated[Optional[StrictStr], Field(description="Whether the resulting activity should be marked as having been performed on a trainer.")] = None, commute : Annotated[Optional[StrictStr], Field(description="Whether the resulting activity should be tagged as a commute.")] = None, data_type : Annotated[Optional[StrictStr], Field(description="The format of the uploaded file.")] = None, external_id : Annotated[Optional[StrictStr], Field(description="The desired external identifier of the resulting activity.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Upload Activity  # noqa: E501

        Uploads a new data file to create an activity from. Requires activity:write scope.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_upload_with_http_info(file, name, description, trainer, commute, data_type, external_id, async_req=True)
        >>> result = thread.get()

        :param file: The uploaded file.
        :type file: bytearray
        :param name: The desired name of the resulting activity.
        :type name: str
        :param description: The desired description of the resulting activity.
        :type description: str
        :param trainer: Whether the resulting activity should be marked as having been performed on a trainer.
        :type trainer: str
        :param commute: Whether the resulting activity should be tagged as a commute.
        :type commute: str
        :param data_type: The format of the uploaded file.
        :type data_type: str
        :param external_id: The desired external identifier of the resulting activity.
        :type external_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Upload, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'file',
            'name',
            'description',
            'trainer',
            'commute',
            'data_type',
            'external_id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_upload" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        if _params['file']:
            _files['file'] = _params['file']

        if _params['name']:
            _form_params.append(('name', _params['name']))

        if _params['description']:
            _form_params.append(('description', _params['description']))

        if _params['trainer']:
            _form_params.append(('trainer', _params['trainer']))

        if _params['commute']:
            _form_params.append(('commute', _params['commute']))

        if _params['data_type']:
            _form_params.append(('data_type', _params['data_type']))

        if _params['external_id']:
            _form_params.append(('external_id', _params['external_id']))

        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['multipart/form-data']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['strava_oauth']  # noqa: E501

        _response_types_map = {
            '201': "Upload",
        }

        return self.api_client.call_api(
            '/uploads', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_upload_by_id(self, upload_id : Annotated[StrictInt, Field(..., description="The identifier of the upload.")], **kwargs) -> Upload:  # noqa: E501
        """Get Upload  # noqa: E501

        Returns an upload for a given identifier. Requires activity:write scope.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_upload_by_id(upload_id, async_req=True)
        >>> result = thread.get()

        :param upload_id: The identifier of the upload. (required)
        :type upload_id: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Upload
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            raise ValueError("Error! Please call the get_upload_by_id_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
        return self.get_upload_by_id_with_http_info(upload_id, **kwargs)  # noqa: E501

    @validate_arguments
    def get_upload_by_id_with_http_info(self, upload_id : Annotated[StrictInt, Field(..., description="The identifier of the upload.")], **kwargs) -> ApiResponse:  # noqa: E501
        """Get Upload  # noqa: E501

        Returns an upload for a given identifier. Requires activity:write scope.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_upload_by_id_with_http_info(upload_id, async_req=True)
        >>> result = thread.get()

        :param upload_id: The identifier of the upload. (required)
        :type upload_id: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the 
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Upload, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'upload_id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_upload_by_id" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['upload_id']:
            _path_params['uploadId'] = _params['upload_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['strava_oauth']  # noqa: E501

        _response_types_map = {
            '200': "Upload",
        }

        return self.api_client.call_api(
            '/uploads/{uploadId}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
